### ISSUE TITLE
 Error when running bundle exec rake db:migrate

### ISSUE THREAD

**Issue by jackastner** [vmeow/f2pehp#1]
I ran into an error setting up the development version of the website.
[migrate_err.log](https://github.com/vmeow/f2pehp/files/3218969/migrate_err.log)

This patch worked for me but, it may or may not be reasonable in the context of the whole website.
[0001-Fix-migrate-file.patch.txt](https://github.com/vmeow/f2pehp/files/3218970/0001-Fix-migrate-file.patch.txt)

**Comment by vmeow** [comment]
Addressed in branch ISSUE-1 which has been merged.
