### ISSUE TITLE
clan admin page is affected by clan filters

### ISSUE THREAD

**Issue by vmeow** [vmeow/f2pehp#113]
Sometimes a 500 error occurs when using the clan admin page, but is fixed by clearing filters using the "Clear Filters" button on the clan page (or visiting https://www.f2p.wiki/clans/W_385?clear_filters=true)

Filters shouldn't affect admin page in the first place, so this is definitely a bug

**Comment by puremana** [comment]
Can't seem to replicate the issue 🤔 , could write some code to fix it but wouldn't know if it would work without replicating it

**Comment by vmeow** [comment]
if not replicable, let's close this. have not seen other reports since then, so it could maybe just be immediate-post-release blues that are sorted out now
