### ISSUE TITLE
Hiscores.get_registered_name doesn't work for certain players

### ISSUE THREAD

**Issue by vmeow** [vmeow/f2pehp#27]
I was notified of the "Add Player to Hiscores" feature not working for the player "influentpump", and narrowed it down to that Hiscores.get_registered_name is returning a nil value when it should be returning "InfluentPump".

Any ideas what could be going on here? @mikevoets 

I took a brief look - maybe it's due to the player having relatively low stats and therefore being unranked (ranked >2 million) when trying to look for for the player?

**Comment by vmeow** [comment]
Resolved in latest push to master: https://github.com/vmeow/f2pehp/commit/2b58f9d9cd36b0362e0121887a5d2b0df82e57ea

**Comment by mikevoets** [comment]
Sorry I couldn't come back to you in time. Have been busy with personal stuff. Glad you found a solution!

**Comment by vmeow** [comment]
@mikevoets  Ah hey sorry I thought I had replied earlier. No worries - I totally understand and there is absolutely never any pressure or rush at all - this is meant to be a fun project after all :) Thanks for building a lot of this stuff in the first place!
