### ISSUE TITLE
daily site crashes

### ISSUE THREAD

**Issue by vmeow** [vmeow/f2pehp#31]
I think the sheer volume of daily updates combined with the terribly unresponsive and slow Jagex Hiscores API has resulted in daily site crashes around the time of daily update rake tasks (00:00 GMT for ALL players, 12:00 GMT for about ~1000 players)

I just added Player.created_at and updated_at, which maybe could be used for more efficient player updates.

Perhaps we can run a rake task hourly or so and update players that haven't been updated in over a day? After first manually staggering the values in the database?

**Comment by vmeow** [comment]
Still not sure of the best way to handle this. The timeouts still result in "app crashes" which lead to site down for a while. I'm not sure how to counteract this; maybe if >100 update failures in the last hour, temporarily disable API requests for an hour?

**Comment by puremana** [comment]
I've put some thought into this and I believe the best way would be to pass the players needed to update to an AWS Lambda ruby service which can run all of the queries and scale/spin up more instances if needed to update players at the same time or wait for jagex's terrible timeouts. Even if the site had 100k players, doing it this way should scale.

Whether this means we need to pass the data through an S3 bucket before or after to retrieve it I'm not too sure.

The AWS service could also be written in something asynchronous like Node if that helps.

On the other hand, perhaps this isn't required. I'm going to have a look at the code and see if there are any improvements that stand out

**Comment by vmeow** [comment]
Agreed that AWS would be both a preferred long-term solution as well as a massive improvement. AWS in general has sort of been on the backburner for a while just because of the larger-than-necessary complexity and time to migrate.

All this hinges on Jagex "API" being responsive to 100k simultaneous requests anyways `d:^B` 

I think for now I'm gonna try some infrastructure to temp disable player updates if >100 fail in the last hour

**Comment by puremana** [comment]
Could we just ping one at a time and update throughout the day?

**Comment by vmeow** [comment]
resolved on Jagex's end.
