### ISSUE TITLE
disable de-iron detection

### ISSUE THREAD

**Issue by vmeow** [vmeow/f2pehp#56]
As Jagex hiscores are down, this is and has been causing issues for players being falsely detected as no longer IM/HC/UIM.

**Comment by puremana** [comment]
(Just so I can recall in the future, even though we have already discussed this)

I can't see any reliable quick fix to this issue. I think the only viable fix is to rewrite the core code that decides a players mode which is located in the `fetch_stats` function in `hiscores.rb`
