### ISSUE TITLE
flair does not appear on mobile (Chrome, iPhone)

### ISSUE THREAD

**Issue by vmeow** [vmeow/f2pehp#71]
All other flairs seem to be working fine on mobile, and water9's water rune flair appears fine on my desktop version of Chrome and Firefox, but it does not appear on my mobile version of Chrome:
![image0](https://user-images.githubusercontent.com/23248132/82594266-aa9c0380-9b58-11ea-8370-b30ca754d4e7.png)

**Comment by puremana** [comment]
b2f92e5928a3012caba45e23e87534d03ad8ce38
Thanks Unkie

**Comment by vmeow** [comment]
thanks for closing it :) FYI, issue appears to be due to the base `items/Water_rune.gif` file, it didn't seem to have a thumbnail when I was looking at the file, and maybe that's what mobile browsers are using
