### ISSUE TITLE
player flairs sometimes tricky to update: investigate stale css cache 

### ISSUE THREAD

**Issue by vmeow** [vmeow/f2pehp#86]

**Comment by puremana** [comment]
One issue relating to this seems to be whenever I add a flair that is already referenced somewhere in the code, it doesn't display

**Comment by puremana** [comment]
The reason this was happening was the SCSS wasn't recompiling when you reference an already existing flair. The solution is to add a comment to force the SCSS to recompile. We are currently doing this in the players.scss.erb file.
